### ISSUE TITLE
Create PostgreSQL database in docker

### ISSUE THREAD

**Issue by pd-dudkiewicz** [Fit-Tracker-Spring-Boot/FitTracker#3]
Create a script that would set up PostgreSQL database in a container. Include pgadmin service as per example.

https://www.docker.com/

https://github.com/felipewom/docker-compose-postgres

To be verified by making `SELECT 1` query on the database.

**Comment by PiotrMichalak1** [comment]
![Image](https://github.com/Fit-Tracker-Spring-Boot/FitTracker/assets/128514914/da8cbfc8-5198-4a2c-a576-8ebe7331f9cf)
